###############################################################
###              User authentication [/auth/*]              ###
###############################################################
### Sign up
POST http://localhost:3001/v1/auth/signup
Content-Type: application/json

{
  "name": "Islam",
  "email": "islam@gmail.com",
  "password": "securePassword123"
}

### Login
POST http://localhost:3001/v1/auth/login
Content-Type: application/json

{
  "email": "islam@gmail.com",
  "password": "securePassword123"
}

### Logout
POST http://localhost:3001/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJpMTc1VW1wbldVbmhxcVE1a0xGQ0YiLCJyb2xlIjoiZ3Vlc3QiLCJpYXQiOjE3Mjk2OTE4NDksImV4cCI6MTcyOTc3ODI0OX0.zXJz4SJhD1xRnBUWEVUqBkSR6oN9LnylB9lU0c3Ws6U

### Get authenticated user info
GET http://localhost:3001/v1/auth/whoami
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNCIsImlhdCI6MTcyOTY5MDY5OCwiZXhwIjoxNzI5Nzc3MDk4fQ.8InzHbWH3P7MMWa0-TLi1FpCSY6jnM5OwiTDS0am46M
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzI5NzA0MTYwLCJleHAiOjE3Mjk3OTA1NjB9.-R7NC3vPI4KIFPS9Y_H4ohFgEkaep5BC8juBYaUIElY


### Generate a new guest token
POST http://localhost:3001/v1/auth/guest-id


###############################################################
###               URL shortening [/links/*]                 ###
###############################################################
### Create shortened URL
POST http://localhost:3001/v1/links
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzI5NzA0MzQxLCJleHAiOjE3Mjk3OTA3NDF9.0_sZ-AoQR8_HrBSEtDOzyxn4HGHQF09NmDZJgYJ5XoY

{
  "label": "Islam link",
  "originalUrl": "https://aya-sdm.com"
}


### Get links created by Authenticated User
GET http://localhost:3001/v1/links
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzI5NzA0MzQxLCJleHAiOjE3Mjk3OTA3NDF9.0_sZ-AoQR8_HrBSEtDOzyxn4HGHQF09NmDZJgYJ5XoY

### Get link by id created by Authenticated User
GET http://localhost:3001/v1/links/1
Authorization: Bearer YOUR_JWT_TOKEN


### Update a Shortened URL
PATCH http://localhost:3001/v1/links/123456
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "label": "New name",
  "originalUrl": "https://example.com/updated-url"
}

### Delete a Shortened URL
DELETE http://localhost:3001/v1/links/123456
Authorization: Bearer YOUR_JWT_TOKEN


###############################################################
###               Analytics [/analytics/*]                  ###
###############################################################

### Get Analytics for a Specific Shortened URL
GET http://localhost:3001/v1/analytics/shortUrl123
Authorization: Bearer YOUR_JWT_TOKEN

###############################################################
###            Redirection [/r/*] [/redirect/*]             ###
###############################################################

### Redirect to a shorten URL
GET http://localhost:3001/v1/redirect/wp6Wqm8

### Redirect to a shorten URL (alias)
GET http://localhost:3001/v1/r/RjL6L0U