###############################################################
###              User authentication [/auth/*]              ###
###############################################################
### Sign up
POST http://localhost:3001/v1/auth/signup
Content-Type: application/json

{
  "label": "Ahmad",
  "email": "user@example.com",
  "password": "securePassword123"
}

### Login
POST http://localhost:3001/v1/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "securePassword123"
}

### Logout
POST http://localhost:3001/v1/auth/logout
Authorization: Bearer YOUR_JWT_TOKEN

### Get authenticated user info
GET http://localhost:3001/v1/auth/me
Authorization: Bearer YOUR_JWT_TOKEN

###############################################################
###               URL shortening [/links/*]                 ###
###############################################################
### Create shortened URL
POST http://localhost:3001/v1/links
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "label": "Some name",
  "originalUrl": "https://example.com/very-long-url"
}


### Get links created by Authenticated User
GET http://localhost:3001/v1/links
Authorization: Bearer YOUR_JWT_TOKEN

### Get link by id created by Authenticated User
GET http://localhost:3001/v1/links/1
Authorization: Bearer YOUR_JWT_TOKEN


### Update a Shortened URL
PATCH http://localhost:3001/v1/links/123456
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "label": "New name",
  "originalUrl": "https://example.com/updated-url"
}

### Delete a Shortened URL
DELETE http://localhost:3001/v1/links/123456
Authorization: Bearer YOUR_JWT_TOKEN


###############################################################
###               Analytics [/analytics/*]                  ###
###############################################################

### Get Analytics for a Specific Shortened URL
GET http://localhost:3001/v1/analytics/shortUrl123
Authorization: Bearer YOUR_JWT_TOKEN

###############################################################
###            Redirection [/r/*] [/redirect/*]             ###
###############################################################

### Redirect to a shorten URL
GET http://localhost:3001/v1/redirect/wp6Wqm8

### Redirect to a shorten URL (alias)
GET http://localhost:3001/v1/r/wp6Wqm8