### User authentication

# Sign up
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
  "name": "Ahmad",
  "email": "user@example.com",
  "password": "securePassword123"
}

# Login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "securePassword123"
}

# Logout
POST http://localhost:3001/api/auth/logout
Authorization: Bearer YOUR_JWT_TOKEN

# Get authenticated user info
GET http://localhost:3001/api/auth/me
Authorization: Bearer YOUR_JWT_TOKEN


### URL shortening

# Create shortened URL (Guest)
POST http://localhost:3001/api/links
Content-Type: application/json

{
  "name": "Some name",
  "originalUrl": "https://example.com/very-long-url",
  "guestId": "guest_123abc"
}

# Create shortened URL (Authenticated User)
POST http://localhost:3001/api/links
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "name": "Some name",
  "originalUrl": "https://example.com/very-long-url"
}

# Redirect to the original URL
GET http://localhost:3001/:shortUrl


### Link Management

# Get links created by Authenticated User
GET http://localhost:3001/api/links
Authorization: Bearer YOUR_JWT_TOKEN

# Get Links Created by Guest User
GET http://localhost:3001/api/links?guestId=guest_123abc

# Update a Shortened URL (Authenticated User)
PATCH http://localhost:3001/api/links/123456
Content-Type: application/json
Authorization: Bearer YOUR_JWT_TOKEN

{
  "name": "New name",
  "originalUrl": "https://example.com/updated-url"
}

# Delete a Shortened URL (Authenticated User)
DELETE http://localhost:3001/api/links/123456
Authorization: Bearer YOUR_JWT_TOKEN


### Analytics

# Get Analytics for a Specific Shortened URL
GET http://localhost:3001/api/analytics/shortUrl123
Authorization: Bearer YOUR_JWT_TOKEN

